# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ap_hccd_report.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ap_hccd_report.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\037com.ruckuswireless.scg.protobuf'),
  serialized_pb=_b('\n\x14\x61p_hccd_report.proto\x1a\x0cnanopb.proto\"\xd7\x02\n\x1c\x41pHccdClientReportConnection\x12\x12\n\nclient_mac\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x19\n\x11\x63onnection_status\x18\x03 \x01(\x05\x12\x15\n\rfailed_msg_id\x18\x04 \x01(\x05\x12\x13\n\x0bmessage_ids\x18\x05 \x03(\x05\x12\x0f\n\x07wlan_id\x18\x06 \x01(\r\x12\x10\n\x08radio_id\x18\x07 \x01(\r\x12\x0c\n\x04ssid\x18\x08 \x01(\t\x12\x10\n\x08wlanType\x18\t \x01(\t\x12\x0b\n\x03snr\x18\n \x01(\x02\x12\x14\n\x0c\x66\x61ilure_type\x18\x0b \x01(\x05\x12\x0c\n\x04vlan\x18\x0c \x01(\x05\x12\x13\n\x0breason_code\x18\r \x01(\x05\x12\x0c\n\x04info\x18\x0e \x01(\t\x12\x0b\n\x03TTF\x18\x0f \x01(\x04\x12\x11\n\tisRoaming\x18\x10 \x01(\x05\x12\x12\n\npktCapName\x18\x11 \x01(\t\"\xd0\x03\n\x13\x41pHccdReportMessage\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0e\n\x06\x61p_mac\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x11\n\tseqNumber\x18\x04 \x01(\x04\x12\x0f\n\x07zone_id\x18\x05 \x01(\t\x12\x12\n\napgroup_id\x18\x06 \x01(\t\x12\x12\n\ncluster_id\x18\x07 \x01(\t\x12\x11\n\tdomain_id\x18\x08 \x01(\t\x12\x13\n\x0b\x61ptenant_id\x18\t \x01(\t\x12\x0e\n\x06map_id\x18\n \x01(\t\x12\x12\n\ndeviceName\x18\x0b \x01(\t\x12\x15\n\raptenant_name\x18\x0c \x01(\t\x12\x11\n\tzone_name\x18\r \x01(\t\x12\x14\n\x0c\x61pgroup_name\x18\x0e \x01(\t\x12\x13\n\x0b\x64omain_name\x18\x0f \x01(\t\x12\x12\n\nsampleTime\x18\x10 \x01(\x04\x12\x1b\n\x13\x61ggregationInterval\x18\x11 \x01(\r\x12\x13\n\x0b\x61pIpAddress\x18\x12 \x01(\t\x12\x15\n\rapIpv6Address\x18\x13 \x01(\t\x12;\n\rapHccdClients\x18\x14 \x03(\x0b\x32\x1d.ApHccdClientReportConnectionB\x05\x92?\x02\x18\x04\x42!\n\x1f\x63om.ruckuswireless.scg.protobuf')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_APHCCDCLIENTREPORTCONNECTION = _descriptor.Descriptor(
  name='ApHccdClientReportConnection',
  full_name='ApHccdClientReportConnection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_mac', full_name='ApHccdClientReportConnection.client_mac', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ApHccdClientReportConnection.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection_status', full_name='ApHccdClientReportConnection.connection_status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failed_msg_id', full_name='ApHccdClientReportConnection.failed_msg_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_ids', full_name='ApHccdClientReportConnection.message_ids', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlan_id', full_name='ApHccdClientReportConnection.wlan_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radio_id', full_name='ApHccdClientReportConnection.radio_id', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ssid', full_name='ApHccdClientReportConnection.ssid', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlanType', full_name='ApHccdClientReportConnection.wlanType', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snr', full_name='ApHccdClientReportConnection.snr', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failure_type', full_name='ApHccdClientReportConnection.failure_type', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vlan', full_name='ApHccdClientReportConnection.vlan', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason_code', full_name='ApHccdClientReportConnection.reason_code', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='ApHccdClientReportConnection.info', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TTF', full_name='ApHccdClientReportConnection.TTF', index=14,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isRoaming', full_name='ApHccdClientReportConnection.isRoaming', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pktCapName', full_name='ApHccdClientReportConnection.pktCapName', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=382,
)


_APHCCDREPORTMESSAGE = _descriptor.Descriptor(
  name='ApHccdReportMessage',
  full_name='ApHccdReportMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ApHccdReportMessage.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ap_mac', full_name='ApHccdReportMessage.ap_mac', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ApHccdReportMessage.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqNumber', full_name='ApHccdReportMessage.seqNumber', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zone_id', full_name='ApHccdReportMessage.zone_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apgroup_id', full_name='ApHccdReportMessage.apgroup_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='ApHccdReportMessage.cluster_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain_id', full_name='ApHccdReportMessage.domain_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aptenant_id', full_name='ApHccdReportMessage.aptenant_id', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map_id', full_name='ApHccdReportMessage.map_id', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='ApHccdReportMessage.deviceName', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aptenant_name', full_name='ApHccdReportMessage.aptenant_name', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zone_name', full_name='ApHccdReportMessage.zone_name', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apgroup_name', full_name='ApHccdReportMessage.apgroup_name', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain_name', full_name='ApHccdReportMessage.domain_name', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sampleTime', full_name='ApHccdReportMessage.sampleTime', index=15,
      number=16, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aggregationInterval', full_name='ApHccdReportMessage.aggregationInterval', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apIpAddress', full_name='ApHccdReportMessage.apIpAddress', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apIpv6Address', full_name='ApHccdReportMessage.apIpv6Address', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apHccdClients', full_name='ApHccdReportMessage.apHccdClients', index=19,
      number=20, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\030\004'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=849,
)

_APHCCDREPORTMESSAGE.fields_by_name['apHccdClients'].message_type = _APHCCDCLIENTREPORTCONNECTION
DESCRIPTOR.message_types_by_name['ApHccdClientReportConnection'] = _APHCCDCLIENTREPORTCONNECTION
DESCRIPTOR.message_types_by_name['ApHccdReportMessage'] = _APHCCDREPORTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApHccdClientReportConnection = _reflection.GeneratedProtocolMessageType('ApHccdClientReportConnection', (_message.Message,), {
  'DESCRIPTOR' : _APHCCDCLIENTREPORTCONNECTION,
  '__module__' : 'ap_hccd_report_pb2'
  # @@protoc_insertion_point(class_scope:ApHccdClientReportConnection)
  })
_sym_db.RegisterMessage(ApHccdClientReportConnection)

ApHccdReportMessage = _reflection.GeneratedProtocolMessageType('ApHccdReportMessage', (_message.Message,), {
  'DESCRIPTOR' : _APHCCDREPORTMESSAGE,
  '__module__' : 'ap_hccd_report_pb2'
  # @@protoc_insertion_point(class_scope:ApHccdReportMessage)
  })
_sym_db.RegisterMessage(ApHccdReportMessage)


DESCRIPTOR._options = None
_APHCCDREPORTMESSAGE.fields_by_name['apHccdClients']._options = None
# @@protoc_insertion_point(module_scope)
