# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ap_mesh.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ap_mesh.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\037com.ruckuswireless.scg.protobuf'),
  serialized_pb=_b('\n\rap_mesh.proto\"\x83\x01\n\x0e\x41PMeshDownlink\x12\x0f\n\x07\x64ownMac\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x0c\n\x04rssi\x18\x03 \x01(\x05\x12\x0f\n\x07txBytes\x18\x04 \x01(\x04\x12\x10\n\x08txFrames\x18\x05 \x01(\x04\x12\x0f\n\x07rxBytes\x18\x06 \x01(\x04\x12\x10\n\x08rxFrames\x18\x07 \x01(\x04\"\x7f\n\x0c\x41PMeshUplink\x12\r\n\x05upMac\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x0c\n\x04rssi\x18\x03 \x01(\x05\x12\x0f\n\x07txBytes\x18\x04 \x01(\x04\x12\x10\n\x08txFrames\x18\x05 \x01(\x04\x12\x0f\n\x07rxBytes\x18\x06 \x01(\x04\x12\x10\n\x08rxFrames\x18\x07 \x01(\x04\"+\n\x0e\x41PMeshNeighbor\x12\x0b\n\x03mac\x18\x01 \x02(\t\x12\x0c\n\x04rssi\x18\x02 \x01(\x05\"\xa5\x04\n\x0b\x41PMeshStats\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\n\n\x02\x61p\x18\x02 \x02(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x11\n\tseqNumber\x18\x04 \x01(\x04\x12\x0f\n\x07zone_id\x18\x05 \x01(\t\x12\x10\n\x08meshRole\x18\x06 \x01(\x05\x12\x10\n\x08meshSSID\x18\x07 \x01(\t\x12\x19\n\x11meshPassphraseMD5\x18\x08 \x01(\t\x12\x0c\n\x04hops\x18\t \x01(\x05\x12!\n\x08neighbor\x18\n \x03(\x0b\x32\x0f.APMeshNeighbor\x12\x1d\n\x06uplink\x18\x0b \x03(\x0b\x32\r.APMeshUplink\x12!\n\x08\x64ownlink\x18\x0c \x03(\x0b\x32\x0f.APMeshDownlink\x12\x12\n\napgroup_id\x18\r \x01(\t\x12\x12\n\ncluster_id\x18\x0e \x01(\t\x12\x11\n\tdomain_id\x18\x0f \x01(\t\x12\x13\n\x0b\x61ptenant_id\x18\x10 \x01(\t\x12\x0e\n\x06map_id\x18\x11 \x01(\t\x12\x15\n\raptenant_name\x18\x12 \x01(\t\x12\x11\n\tzone_name\x18\x13 \x01(\t\x12\x14\n\x0c\x61pgroup_name\x18\x14 \x01(\t\x12\x13\n\x0b\x64omain_name\x18\x15 \x01(\t\x12\x12\n\nsampleTime\x18\x16 \x01(\x04\x12\x1b\n\x13\x61ggregationInterval\x18\x17 \x01(\r\x12\x14\n\x0cisMeshEnable\x18\x18 \x01(\x08\x12\x14\n\x0cserialNumber\x18\x19 \x01(\tB!\n\x1f\x63om.ruckuswireless.scg.protobuf')
)




_APMESHDOWNLINK = _descriptor.Descriptor(
  name='APMeshDownlink',
  full_name='APMeshDownlink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='downMac', full_name='APMeshDownlink.downMac', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='APMeshDownlink.type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rssi', full_name='APMeshDownlink.rssi', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txBytes', full_name='APMeshDownlink.txBytes', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txFrames', full_name='APMeshDownlink.txFrames', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rxBytes', full_name='APMeshDownlink.rxBytes', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rxFrames', full_name='APMeshDownlink.rxFrames', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=149,
)


_APMESHUPLINK = _descriptor.Descriptor(
  name='APMeshUplink',
  full_name='APMeshUplink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upMac', full_name='APMeshUplink.upMac', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='APMeshUplink.type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rssi', full_name='APMeshUplink.rssi', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txBytes', full_name='APMeshUplink.txBytes', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txFrames', full_name='APMeshUplink.txFrames', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rxBytes', full_name='APMeshUplink.rxBytes', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rxFrames', full_name='APMeshUplink.rxFrames', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=278,
)


_APMESHNEIGHBOR = _descriptor.Descriptor(
  name='APMeshNeighbor',
  full_name='APMeshNeighbor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac', full_name='APMeshNeighbor.mac', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rssi', full_name='APMeshNeighbor.rssi', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=323,
)


_APMESHSTATS = _descriptor.Descriptor(
  name='APMeshStats',
  full_name='APMeshStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='APMeshStats.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ap', full_name='APMeshStats.ap', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='APMeshStats.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqNumber', full_name='APMeshStats.seqNumber', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zone_id', full_name='APMeshStats.zone_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meshRole', full_name='APMeshStats.meshRole', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meshSSID', full_name='APMeshStats.meshSSID', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meshPassphraseMD5', full_name='APMeshStats.meshPassphraseMD5', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hops', full_name='APMeshStats.hops', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighbor', full_name='APMeshStats.neighbor', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uplink', full_name='APMeshStats.uplink', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='downlink', full_name='APMeshStats.downlink', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apgroup_id', full_name='APMeshStats.apgroup_id', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='APMeshStats.cluster_id', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain_id', full_name='APMeshStats.domain_id', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aptenant_id', full_name='APMeshStats.aptenant_id', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map_id', full_name='APMeshStats.map_id', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aptenant_name', full_name='APMeshStats.aptenant_name', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zone_name', full_name='APMeshStats.zone_name', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apgroup_name', full_name='APMeshStats.apgroup_name', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain_name', full_name='APMeshStats.domain_name', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sampleTime', full_name='APMeshStats.sampleTime', index=21,
      number=22, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aggregationInterval', full_name='APMeshStats.aggregationInterval', index=22,
      number=23, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isMeshEnable', full_name='APMeshStats.isMeshEnable', index=23,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialNumber', full_name='APMeshStats.serialNumber', index=24,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=875,
)

_APMESHSTATS.fields_by_name['neighbor'].message_type = _APMESHNEIGHBOR
_APMESHSTATS.fields_by_name['uplink'].message_type = _APMESHUPLINK
_APMESHSTATS.fields_by_name['downlink'].message_type = _APMESHDOWNLINK
DESCRIPTOR.message_types_by_name['APMeshDownlink'] = _APMESHDOWNLINK
DESCRIPTOR.message_types_by_name['APMeshUplink'] = _APMESHUPLINK
DESCRIPTOR.message_types_by_name['APMeshNeighbor'] = _APMESHNEIGHBOR
DESCRIPTOR.message_types_by_name['APMeshStats'] = _APMESHSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

APMeshDownlink = _reflection.GeneratedProtocolMessageType('APMeshDownlink', (_message.Message,), {
  'DESCRIPTOR' : _APMESHDOWNLINK,
  '__module__' : 'ap_mesh_pb2'
  # @@protoc_insertion_point(class_scope:APMeshDownlink)
  })
_sym_db.RegisterMessage(APMeshDownlink)

APMeshUplink = _reflection.GeneratedProtocolMessageType('APMeshUplink', (_message.Message,), {
  'DESCRIPTOR' : _APMESHUPLINK,
  '__module__' : 'ap_mesh_pb2'
  # @@protoc_insertion_point(class_scope:APMeshUplink)
  })
_sym_db.RegisterMessage(APMeshUplink)

APMeshNeighbor = _reflection.GeneratedProtocolMessageType('APMeshNeighbor', (_message.Message,), {
  'DESCRIPTOR' : _APMESHNEIGHBOR,
  '__module__' : 'ap_mesh_pb2'
  # @@protoc_insertion_point(class_scope:APMeshNeighbor)
  })
_sym_db.RegisterMessage(APMeshNeighbor)

APMeshStats = _reflection.GeneratedProtocolMessageType('APMeshStats', (_message.Message,), {
  'DESCRIPTOR' : _APMESHSTATS,
  '__module__' : 'ap_mesh_pb2'
  # @@protoc_insertion_point(class_scope:APMeshStats)
  })
_sym_db.RegisterMessage(APMeshStats)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
