# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sci-configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sci-configuration.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n#com.ruckuswireless.scg.protobuf.sci'),
  serialized_pb=_b('\n\x17sci-configuration.proto\"`\n\x14\x43onfigurationMessage\x12\x0f\n\x07version\x18\x01 \x02(\r\x12$\n\x0b\x63lusterInfo\x18\x02 \x01(\x0b\x32\x0f.ClusterMessage\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\"\x90\x02\n\x0e\x43lusterMessage\x12\x13\n\x0b\x63lusterUuid\x18\x01 \x01(\t\x12\x13\n\x0b\x63lusterName\x18\x02 \x01(\t\x12\x15\n\rcontrolBlades\x18\x03 \x01(\t\x12\x1e\n\x16\x63ontrollerUtilizations\x18\x04 \x01(\t\x12\x15\n\rsystemSummary\x18\x05 \x01(\t\x12\x0f\n\x07\x64omains\x18\x64 \x01(\t\x12\r\n\x05zones\x18\x65 \x01(\t\x12\x10\n\x08\x61pGroups\x18\x66 \x01(\t\x12\x12\n\nwlanGroups\x18g \x01(\t\x12\r\n\x05wlans\x18h \x01(\t\x12\x0b\n\x03\x61ps\x18i \x01(\t\x12$\n\x0btenantInfos\x18\xc8\x01 \x03(\x0b\x32\x0e.TenantMessage\"Z\n\rTenantMessage\x12\x10\n\x08tenantId\x18\x01 \x01(\t\x12\x12\n\ntenantName\x18\x02 \x01(\t\x12#\n\x0b\x61\x64minDomain\x18\x03 \x01(\x0b\x32\x0e.DomainMessage\"~\n\rDomainMessage\x12\x10\n\x08\x64omainId\x18\x01 \x01(\t\x12\x12\n\ndomainName\x18\x02 \x01(\t\x12\x1f\n\tzoneInfos\x18\x03 \x03(\x0b\x32\x0c.ZoneMessage\x12&\n\x0esubDomainInfos\x18\x04 \x03(\x0b\x32\x0e.DomainMessage\"\x81\x01\n\x0bZoneMessage\x12\x0e\n\x06zoneId\x18\x01 \x01(\t\x12\x10\n\x08zoneName\x18\x02 \x01(\t\x12%\n\x0c\x61pGroupInfos\x18\x03 \x03(\x0b\x32\x0f.ApGroupMessage\x12)\n\x0ewlanGroupInfos\x18\x04 \x03(\x0b\x32\x11.WlanGroupMessage\"8\n\x0e\x41pGroupMessage\x12\x11\n\tapGroupId\x18\x01 \x01(\t\x12\x13\n\x0b\x61pGroupName\x18\x02 \x01(\t\">\n\x10WlanGroupMessage\x12\x13\n\x0bwlanGroupId\x18\x01 \x01(\t\x12\x15\n\rwlanGroupName\x18\x02 \x01(\tB%\n#com.ruckuswireless.scg.protobuf.sci')
)




_CONFIGURATIONMESSAGE = _descriptor.Descriptor(
  name='ConfigurationMessage',
  full_name='ConfigurationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ConfigurationMessage.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterInfo', full_name='ConfigurationMessage.clusterInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ConfigurationMessage.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=123,
)


_CLUSTERMESSAGE = _descriptor.Descriptor(
  name='ClusterMessage',
  full_name='ClusterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterUuid', full_name='ClusterMessage.clusterUuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterName', full_name='ClusterMessage.clusterName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controlBlades', full_name='ClusterMessage.controlBlades', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controllerUtilizations', full_name='ClusterMessage.controllerUtilizations', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='systemSummary', full_name='ClusterMessage.systemSummary', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domains', full_name='ClusterMessage.domains', index=5,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zones', full_name='ClusterMessage.zones', index=6,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apGroups', full_name='ClusterMessage.apGroups', index=7,
      number=102, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlanGroups', full_name='ClusterMessage.wlanGroups', index=8,
      number=103, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlans', full_name='ClusterMessage.wlans', index=9,
      number=104, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aps', full_name='ClusterMessage.aps', index=10,
      number=105, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tenantInfos', full_name='ClusterMessage.tenantInfos', index=11,
      number=200, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=398,
)


_TENANTMESSAGE = _descriptor.Descriptor(
  name='TenantMessage',
  full_name='TenantMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tenantId', full_name='TenantMessage.tenantId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tenantName', full_name='TenantMessage.tenantName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adminDomain', full_name='TenantMessage.adminDomain', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=490,
)


_DOMAINMESSAGE = _descriptor.Descriptor(
  name='DomainMessage',
  full_name='DomainMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domainId', full_name='DomainMessage.domainId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainName', full_name='DomainMessage.domainName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoneInfos', full_name='DomainMessage.zoneInfos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subDomainInfos', full_name='DomainMessage.subDomainInfos', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=618,
)


_ZONEMESSAGE = _descriptor.Descriptor(
  name='ZoneMessage',
  full_name='ZoneMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zoneId', full_name='ZoneMessage.zoneId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoneName', full_name='ZoneMessage.zoneName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apGroupInfos', full_name='ZoneMessage.apGroupInfos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlanGroupInfos', full_name='ZoneMessage.wlanGroupInfos', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=750,
)


_APGROUPMESSAGE = _descriptor.Descriptor(
  name='ApGroupMessage',
  full_name='ApGroupMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apGroupId', full_name='ApGroupMessage.apGroupId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apGroupName', full_name='ApGroupMessage.apGroupName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=752,
  serialized_end=808,
)


_WLANGROUPMESSAGE = _descriptor.Descriptor(
  name='WlanGroupMessage',
  full_name='WlanGroupMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wlanGroupId', full_name='WlanGroupMessage.wlanGroupId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlanGroupName', full_name='WlanGroupMessage.wlanGroupName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=810,
  serialized_end=872,
)

_CONFIGURATIONMESSAGE.fields_by_name['clusterInfo'].message_type = _CLUSTERMESSAGE
_CLUSTERMESSAGE.fields_by_name['tenantInfos'].message_type = _TENANTMESSAGE
_TENANTMESSAGE.fields_by_name['adminDomain'].message_type = _DOMAINMESSAGE
_DOMAINMESSAGE.fields_by_name['zoneInfos'].message_type = _ZONEMESSAGE
_DOMAINMESSAGE.fields_by_name['subDomainInfos'].message_type = _DOMAINMESSAGE
_ZONEMESSAGE.fields_by_name['apGroupInfos'].message_type = _APGROUPMESSAGE
_ZONEMESSAGE.fields_by_name['wlanGroupInfos'].message_type = _WLANGROUPMESSAGE
DESCRIPTOR.message_types_by_name['ConfigurationMessage'] = _CONFIGURATIONMESSAGE
DESCRIPTOR.message_types_by_name['ClusterMessage'] = _CLUSTERMESSAGE
DESCRIPTOR.message_types_by_name['TenantMessage'] = _TENANTMESSAGE
DESCRIPTOR.message_types_by_name['DomainMessage'] = _DOMAINMESSAGE
DESCRIPTOR.message_types_by_name['ZoneMessage'] = _ZONEMESSAGE
DESCRIPTOR.message_types_by_name['ApGroupMessage'] = _APGROUPMESSAGE
DESCRIPTOR.message_types_by_name['WlanGroupMessage'] = _WLANGROUPMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigurationMessage = _reflection.GeneratedProtocolMessageType('ConfigurationMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATIONMESSAGE,
  '__module__' : 'sci_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ConfigurationMessage)
  })
_sym_db.RegisterMessage(ConfigurationMessage)

ClusterMessage = _reflection.GeneratedProtocolMessageType('ClusterMessage', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERMESSAGE,
  '__module__' : 'sci_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ClusterMessage)
  })
_sym_db.RegisterMessage(ClusterMessage)

TenantMessage = _reflection.GeneratedProtocolMessageType('TenantMessage', (_message.Message,), {
  'DESCRIPTOR' : _TENANTMESSAGE,
  '__module__' : 'sci_configuration_pb2'
  # @@protoc_insertion_point(class_scope:TenantMessage)
  })
_sym_db.RegisterMessage(TenantMessage)

DomainMessage = _reflection.GeneratedProtocolMessageType('DomainMessage', (_message.Message,), {
  'DESCRIPTOR' : _DOMAINMESSAGE,
  '__module__' : 'sci_configuration_pb2'
  # @@protoc_insertion_point(class_scope:DomainMessage)
  })
_sym_db.RegisterMessage(DomainMessage)

ZoneMessage = _reflection.GeneratedProtocolMessageType('ZoneMessage', (_message.Message,), {
  'DESCRIPTOR' : _ZONEMESSAGE,
  '__module__' : 'sci_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ZoneMessage)
  })
_sym_db.RegisterMessage(ZoneMessage)

ApGroupMessage = _reflection.GeneratedProtocolMessageType('ApGroupMessage', (_message.Message,), {
  'DESCRIPTOR' : _APGROUPMESSAGE,
  '__module__' : 'sci_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ApGroupMessage)
  })
_sym_db.RegisterMessage(ApGroupMessage)

WlanGroupMessage = _reflection.GeneratedProtocolMessageType('WlanGroupMessage', (_message.Message,), {
  'DESCRIPTOR' : _WLANGROUPMESSAGE,
  '__module__' : 'sci_configuration_pb2'
  # @@protoc_insertion_point(class_scope:WlanGroupMessage)
  })
_sym_db.RegisterMessage(WlanGroupMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
