# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sci-alarm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sci-alarm.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n#com.ruckuswireless.scg.protobuf.sci'),
  serialized_pb=_b('\n\x0fsci-alarm.proto\"\xba\x04\n\x0c\x41larmMessage\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\talarmUuid\x18\x02 \x01(\t\x12\x11\n\talarmCode\x18\x03 \x01(\r\x12\x15\n\ralarmSeverity\x18\x04 \x01(\t\x12\x14\n\x0cmainCategory\x18\x05 \x01(\t\x12\x11\n\talarmType\x18\x06 \x01(\t\x12\x15\n\rinitEventCode\x18\x07 \x01(\r\x12\x11\n\ttimestamp\x18\x08 \x01(\x04\x12,\n\nalarmState\x18\t \x01(\x0e\x32\x18.AlarmMessage.AlarmState\x12&\n\nattributes\x18\n \x03(\x0b\x32\x12.AlarmMessageEntry\x12\x10\n\x08\x64omainId\x18\x0b \x01(\t\x12\x0e\n\x06zoneId\x18\x0c \x01(\t\x12\x11\n\tapGroupId\x18\r \x01(\t\x12\r\n\x05\x61pMac\x18\x0e \x01(\t\x12\x11\n\tclientMac\x18\x0f \x01(\t\x12\x0e\n\x06reason\x18\x10 \x01(\t\x12\x12\n\ndomainName\x18\x11 \x01(\t\x12\x10\n\x08zoneName\x18\x12 \x01(\t\x12\x13\n\x0b\x61pGroupName\x18\x13 \x01(\t\x12\x13\n\x0b\x61pIpAddress\x18\x14 \x01(\t\x12\x15\n\rapIpv6Address\x18\x15 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x16 \x01(\t\x12\x13\n\x0bsubCategory\x18\x17 \x01(\t\x12\x0f\n\x07\x62ladeId\x18\x18 \x01(\t\"*\n\nAlarmState\x12\x0f\n\x0bOUTSTANDING\x10\x00\x12\x0b\n\x07\x43LEARED\x10\x01\"/\n\x11\x41larmMessageEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB%\n#com.ruckuswireless.scg.protobuf.sci')
)



_ALARMMESSAGE_ALARMSTATE = _descriptor.EnumDescriptor(
  name='AlarmState',
  full_name='AlarmMessage.AlarmState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OUTSTANDING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLEARED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=548,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_ALARMMESSAGE_ALARMSTATE)


_ALARMMESSAGE = _descriptor.Descriptor(
  name='AlarmMessage',
  full_name='AlarmMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='AlarmMessage.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarmUuid', full_name='AlarmMessage.alarmUuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarmCode', full_name='AlarmMessage.alarmCode', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarmSeverity', full_name='AlarmMessage.alarmSeverity', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mainCategory', full_name='AlarmMessage.mainCategory', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarmType', full_name='AlarmMessage.alarmType', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initEventCode', full_name='AlarmMessage.initEventCode', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='AlarmMessage.timestamp', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarmState', full_name='AlarmMessage.alarmState', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='AlarmMessage.attributes', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainId', full_name='AlarmMessage.domainId', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoneId', full_name='AlarmMessage.zoneId', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apGroupId', full_name='AlarmMessage.apGroupId', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apMac', full_name='AlarmMessage.apMac', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientMac', full_name='AlarmMessage.clientMac', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='AlarmMessage.reason', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainName', full_name='AlarmMessage.domainName', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoneName', full_name='AlarmMessage.zoneName', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apGroupName', full_name='AlarmMessage.apGroupName', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apIpAddress', full_name='AlarmMessage.apIpAddress', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apIpv6Address', full_name='AlarmMessage.apIpv6Address', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='AlarmMessage.description', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subCategory', full_name='AlarmMessage.subCategory', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bladeId', full_name='AlarmMessage.bladeId', index=23,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ALARMMESSAGE_ALARMSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=590,
)


_ALARMMESSAGEENTRY = _descriptor.Descriptor(
  name='AlarmMessageEntry',
  full_name='AlarmMessageEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AlarmMessageEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='AlarmMessageEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=639,
)

_ALARMMESSAGE.fields_by_name['alarmState'].enum_type = _ALARMMESSAGE_ALARMSTATE
_ALARMMESSAGE.fields_by_name['attributes'].message_type = _ALARMMESSAGEENTRY
_ALARMMESSAGE_ALARMSTATE.containing_type = _ALARMMESSAGE
DESCRIPTOR.message_types_by_name['AlarmMessage'] = _ALARMMESSAGE
DESCRIPTOR.message_types_by_name['AlarmMessageEntry'] = _ALARMMESSAGEENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlarmMessage = _reflection.GeneratedProtocolMessageType('AlarmMessage', (_message.Message,), {
  'DESCRIPTOR' : _ALARMMESSAGE,
  '__module__' : 'sci_alarm_pb2'
  # @@protoc_insertion_point(class_scope:AlarmMessage)
  })
_sym_db.RegisterMessage(AlarmMessage)

AlarmMessageEntry = _reflection.GeneratedProtocolMessageType('AlarmMessageEntry', (_message.Message,), {
  'DESCRIPTOR' : _ALARMMESSAGEENTRY,
  '__module__' : 'sci_alarm_pb2'
  # @@protoc_insertion_point(class_scope:AlarmMessageEntry)
  })
_sym_db.RegisterMessage(AlarmMessageEntry)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
