# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session_manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ScgSessMgrPubIpc_pb2 as ScgSessMgrPubIpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='session_manager.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n&com.ruckuswireless.scg.protobuf.client'),
  serialized_pb=_b('\n\x15session_manager.proto\x1a\x16ScgSessMgrPubIpc.proto\"\xac\x01\n\x18SessionManagerClientData\x12W\n\x14sessionMgrClientStat\x18\x01 \x01(\x0b\x32\x39.ScgSessMgrPubIpc.GBP_SESSMGR_PUBS_STATS_AP_CLIENT_STAT_T\x12\x37\n\x0f\x65xtraAttributes\x18\x02 \x01(\x0b\x32\x1e.ExtraSessClientDataAttributes\"\x95\x01\n\x1d\x45xtraSessClientDataAttributes\x12\x14\n\x0cserialNumber\x18\x01 \x01(\t\x12\x12\n\ndomainName\x18\x02 \x01(\t\x12\x10\n\x08zoneName\x18\x03 \x01(\t\x12\x11\n\tapGroupId\x18\x04 \x01(\t\x12\x13\n\x0b\x61pGroupName\x18\x05 \x01(\t\x12\x10\n\x08wlanName\x18\x06 \x01(\tB(\n&com.ruckuswireless.scg.protobuf.client')
  ,
  dependencies=[ScgSessMgrPubIpc__pb2.DESCRIPTOR,])




_SESSIONMANAGERCLIENTDATA = _descriptor.Descriptor(
  name='SessionManagerClientData',
  full_name='SessionManagerClientData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionMgrClientStat', full_name='SessionManagerClientData.sessionMgrClientStat', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extraAttributes', full_name='SessionManagerClientData.extraAttributes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=222,
)


_EXTRASESSCLIENTDATAATTRIBUTES = _descriptor.Descriptor(
  name='ExtraSessClientDataAttributes',
  full_name='ExtraSessClientDataAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialNumber', full_name='ExtraSessClientDataAttributes.serialNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainName', full_name='ExtraSessClientDataAttributes.domainName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoneName', full_name='ExtraSessClientDataAttributes.zoneName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apGroupId', full_name='ExtraSessClientDataAttributes.apGroupId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apGroupName', full_name='ExtraSessClientDataAttributes.apGroupName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlanName', full_name='ExtraSessClientDataAttributes.wlanName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=374,
)

_SESSIONMANAGERCLIENTDATA.fields_by_name['sessionMgrClientStat'].message_type = ScgSessMgrPubIpc__pb2._GBP_SESSMGR_PUBS_STATS_AP_CLIENT_STAT_T
_SESSIONMANAGERCLIENTDATA.fields_by_name['extraAttributes'].message_type = _EXTRASESSCLIENTDATAATTRIBUTES
DESCRIPTOR.message_types_by_name['SessionManagerClientData'] = _SESSIONMANAGERCLIENTDATA
DESCRIPTOR.message_types_by_name['ExtraSessClientDataAttributes'] = _EXTRASESSCLIENTDATAATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionManagerClientData = _reflection.GeneratedProtocolMessageType('SessionManagerClientData', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONMANAGERCLIENTDATA,
  '__module__' : 'session_manager_pb2'
  # @@protoc_insertion_point(class_scope:SessionManagerClientData)
  })
_sym_db.RegisterMessage(SessionManagerClientData)

ExtraSessClientDataAttributes = _reflection.GeneratedProtocolMessageType('ExtraSessClientDataAttributes', (_message.Message,), {
  'DESCRIPTOR' : _EXTRASESSCLIENTDATAATTRIBUTES,
  '__module__' : 'session_manager_pb2'
  # @@protoc_insertion_point(class_scope:ExtraSessClientDataAttributes)
  })
_sym_db.RegisterMessage(ExtraSessClientDataAttributes)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
